= Semantic Patches

Coccinelle is an open source tool that can analyze and transform C code according to specified rules creating SmPL (Semantic Patch Language) patches_. Semantic patches are much more powerful than patches or regular expressions. so, that's why we use it.

About Coccinelle

* Official site http://coccinelle.lip6.fr/
* Howto http://coccinelle.lip6.fr/papers/tutorial.pdf
* The SmPL Grammar http://coccinelle.lip6.fr/docs/main_grammar.html
* An Introduction to Coccinelle (video) https://www.youtube.com/watch?v=buZrNd6XkEw

== Maintainer work

All cocci files can be found in `scripts/coccinelle/`.

== Run tests

We have two different modes:

=== 1. Only print the diff output.

[source,shell]
----
$ make coccinelle.diff
----

=== 2. Do the modification on the file directly and print out the diff.

[source,shell]
----
$ make coccinelle.patch
----

== Proposing new semantic patches

New semantic patches can be proposed and submitted. they should be organized by name in `scripts/coccinelle/` with good description inside the script.
